exclude:
  languages

ignore:
  - Tristan Lins <tristan.lins@bit3.de>
  - Tristan Lins <tristan.lins@infinitysoft.de>
  - Avibot <avibot@avisota.org>
  - Christoph Wiechert <wio@psitrax.de>
  - David Maack <david.maack@arcor.de>
  - Oliver Hoff <oliver@hofff.com>
